package entities;

/**
 * Created by A&S on 05/11/2015.
 */
public enum Category {
    ARTS,PHOTOGRAPHY,BIOGRAPHIES,MEMOIRS,CHILDREN,COOK,LITERATURE,HISTORY,
    MYSTERY,SUSPENSE,ROMANCE,SCIENCEFICTION,FANTASY,YOUNGADULT
}
